<?php
/**
 * Assets module.
 *
 * Handles enqueuing of styles and scripts for the frontend.
 *
 * @package YTubeFancy\Modules\Core
 */

declare( strict_types = 1 );

namespace YTubeFancy\Modules\Core;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use YTubeFancy\Contracts\Interfaces\Registrable;

/**
 * Class Assets
 *
 * Enqueues admin and frontend CSS/JS assets, using build-generated
 * asset.php files for dependency and version management.
 */
class Assets implements Registrable {

	/**
	 * Register WordPress hooks.
	 */
	public function register_hooks(): void {
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_frontend_assets' ] );
		add_filter( 'widget_text', 'shortcode_unautop' );
		add_filter( 'widget_text', 'do_shortcode' );
	}

	/**
	 * Enqueue frontend styles and scripts.
	 */
	public function enqueue_frontend_assets(): void {
		if ( function_exists( 'amp_is_request' ) && amp_is_request() ) {
			$asset = $this->get_asset( 'build/css/youtubefancybox-amp.asset.php' );

			wp_enqueue_style(
				'youtubefancybox-amp',
				YTUBE_FANCY_URL . 'build/css/youtubefancybox-amp.css',
				$asset['dependencies'],
				$asset['version']
			);
			return;
		}

		$colorbox_css_asset = $this->get_asset( 'build/css/colorbox.asset.php' );

		wp_enqueue_style(
			'colorbox-css',
			YTUBE_FANCY_URL . 'build/css/colorbox.css',
			$colorbox_css_asset['dependencies'],
			$colorbox_css_asset['version']
		);

		wp_enqueue_script( 'jquery' );

		$colorbox_js_asset = $this->get_asset( 'build/js/jquery.colorbox.asset.php' );

		wp_enqueue_script(
			'colorbox-js',
			YTUBE_FANCY_URL . 'build/js/jquery.colorbox.js',
			$colorbox_js_asset['dependencies'],
			$colorbox_js_asset['version'],
			true
		);

		$caller_asset = $this->get_asset( 'build/js/caller.asset.php' );

		wp_enqueue_script(
			'colorbox-caller',
			YTUBE_FANCY_URL . 'build/js/caller.js',
			$caller_asset['dependencies'],
			$caller_asset['version'],
			true
		);
	}

	/**
	 * Load an asset.php file generated by @wordpress/scripts.
	 *
	 * Falls back to empty dependencies and the plugin version if the file
	 * does not exist.
	 *
	 * @param string $relative_path Relative path from plugin root to the asset.php file.
	 * @return array{ dependencies: string[], version: string } Asset metadata.
	 */
	private function get_asset( string $relative_path ): array { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.Found
		$path = YTUBE_FANCY_DIR . $relative_path;

		if ( file_exists( $path ) ) {
			return require $path; // phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable
		}

		return [
			'dependencies' => [],
			'version'      => YTUBE_FANCY_VERSION,
		];
	}
}
